### ISSUE TITLE
How to change peerflix  to saved videos to home folder instead of tmp

### ISSUE THREAD

**Issue by saurabhShabdik** [mafintosh/peerflix#102]
How to change the folder from tmp to Home 
You have given the command or argument
--f or --path ( change buffer file path )

Please tell me how to press the argument or command

Thanks in advance :) 
P.S. I'm just an average user.

**Comment by SnoOpyMinhThang** [comment]
hey mafintosh,
how to specify buffer path in Windows?
I tried -f "E:\Film", it said "downloaded 250MB" but nothing in E:\Film ?
I can continue to watch movie in MPC, checked in TEMP folder, :(
