### ISSUE TITLE
VLC is unable to open the MRL

### ISSUE THREAD

**Issue by Sheraff** [mafintosh/peerflix#136]
One of my users is reporting the following error:

`VLC is unable to open the MRL 'http://10.0.1.5:8888/'. Check the log for details.`

It used to happen to me when I invoked peerflix and VLC separately. If VLC opened too soon it would return this error. But in the version of the program my user is using, VLC is called through `peerflix -v` so I'm assuming that it is an error.

**Comment by NViper21** [comment]
How do you fix this on windows?
