### ISSUE TITLE
Plugin api

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/peerflix#140]
Create a way for extending the cli with various plugins.
This would allow us to externalize airplay support etc.

**Comment by robertstefan** [comment]
@Sheraff , @mafintosh what is the status of the 
```
peerflix {magnet} --ondownloaded "./myscript.sh" --onserverstarted "./anotherscript.sh"
```
idea? :(

**Comment by Sheraff** [comment]
It's been a while so I don't remember exactly if [this issue i mentionned above](https://github.com/mafintosh/peerflix/issues/140#issuecomment-61380584) got fixed, but it's otherwise implemented in peerflix and totally usable.

**Comment by mafintosh** [comment]
@Sheraff what was the problem with `--on-downloaded` again?

**Comment by Sheraff** [comment]
If I remember correctly, the way it's implemented it counts the download as over if `swarm.downloaded >= filelength` which never actually gets reached if some parts were previously downloaded by another instance of peerflix

**Comment by mafintosh** [comment]
@Sheraff It seems `--on-downloaded` is handled here https://github.com/mafintosh/peerflix/blob/master/app.js#L147-L153. This logic seems pretty sound to me. Maybe we fixed it already? :)

**Comment by Sheraff** [comment]
Ah yeah right I remember committing that (or I think I do, sorry if I'm taking credit for it). In any case, I remember the logic, so **yeah, it's fixed** :-)

**Comment by mafintosh** [comment]
\o/ I'm closing this for now. If events are missing comment here or open a new issue.
