### ISSUE TITLE
Add MPC-HC support

### ISSUE THREAD

**Issue by vBm** [mafintosh/peerflix#157]
@[mpc-hc](https://github.com/mpc-hc/mpc-hc) is one of the windows media players. It has support for loading streams and files ofc. Shouldn't be too hard to add support for it.

Thanks in advance.

**Comment by MaxGfeller** [comment]
Yo @vBm i implemented this but could not quite test it on my virtual machine. Could you try this on your machine? https://github.com/MaxGfeller/peerflix/tree/add-mpc-hc

**Comment by MaxGfeller** [comment]
Alright @vBm, i made a few fixes and now it should work. Could you check with my fork?

**Comment by vBm** [comment]
@MaxGfeller Thank you very much. It works just fine.

Thou I was wondering shouldn't [app.js#L30](https://github.com/MaxGfeller/peerflix/blob/add-mpc-hc/app.js#L30) be something like this:
```diff
+.alias('mpchc', 'mpc-hc').describe('mpchc', 'autoplay in MPC-HC player*').boolean('boolean')
```
instead of:
```diff
-.describe('mpchc', 'autoplay in MPC-HC player*').boolean('boolean')
```


Thanks again :) :+1:

**Comment by MaxGfeller** [comment]
No, an alias can only be one character and there was no obvious one-character alias left to take for mpc-hc :)

Merged the changes into master, @mafintosh can you `npm publish`?

**Comment by mafintosh** [comment]
Yes sir. Released as 0.25.0

**Comment by MaxGfeller** [comment]
Awesome, thanks!

**Comment by vBm** [comment]
Thanks lads.
