### ISSUE TITLE
it could pipe to stdout

### ISSUE THREAD

**Issue by docteurklein** [mafintosh/peerflix#161]
it's just unix, baby. I can't even imagine what possibilities it opens.

This way, no more --vlc (and its options support #124), nor --mplayer, nor a small finite list of supported players.
What if I want to open it with windows media player (troll) ?
One could even pipe to netcat if he wants :)

Is it possible?

**Comment by docteurklein** [comment]
I guess we can close it, even tho the piping is not resolved. 

At best, we can delegate some of its features to vlc (using its arguments).
Thanks, and happy new year :)
PS: awesome work.

**Comment by docteurklein** [comment]
And you're right, maybe a simple torrent-cat script based on your lib might be enough :)

**Comment by onny** [comment]
Can someone provide be a torrent-cat script? I once had a small script like this, found somewhere on the net but I can not remember the name ... :(
