### ISSUE TITLE
VLC Unable to open the MRL 'http://localhost:8888/' I can't stream torrent via VLC !

### ISSUE THREAD

**Issue by Iliyass** [mafintosh/peerflix#162]
hey guys i just installed this module by npm and follow the instructions, 
but when i want to stream the magnet link vlc started but it gives this error 
```
VLC Unable to open the MRL 'http://localhost:8888/' 
```
I'm on MAC OS X Yosemite

**Comment by Iliyass** [comment]
it fixed i just changed the -h arg to 127.0.0.1 and it works thanks man for this wonderful module :D

**Comment by mafintosh** [comment]
awesome!
