### ISSUE TITLE
Selecting video file

### ISSUE THREAD

**Issue by FilmCoder** [mafintosh/peerflix#165]
Sometimes a torrent contains multiple video files within it.  Is there a way to select which video file I can stream within a torrent, instead of just having peerflix default to the largest file?

**Comment by mafintosh** [comment]
Yes. Use `--list` to list the files and `-i` to select one

**Comment by clkao** [comment]
something like inquirer.prompt for choosing a file would be great.

**Comment by mafintosh** [comment]
@clkao send me a pr :)

**Comment by clkao** [comment]
@mafintosh you good with bringing in inquirer and rsvp as deps?

**Comment by mafintosh** [comment]
@clkao as long as it is simple non-frameworky i'm ok with it

**Comment by mafintosh** [comment]
and assuming the don't have any native deps
