### ISSUE TITLE
Peerflix NPAPI

### ISSUE THREAD

**Issue by jaruba** [mafintosh/peerflix#167]
How about making a browser NPAPI plugin based on Peerflix and Firebreath (not sure if it supports node.js)? There aren't any working / stable solutions out there for a plugin that simply plays torrents (except Ace Stream, but they are closed source and do black hat marketing on your PC).

As long as the plugin will be open source and reliable, I can really see this having a place in the online world. I remember Ninja Video (website) that made their own streaming plugin and they had more then 1 million unique visitors daily, so visitors installing a plugin for something like this seems ok to me.

It could come bundled with [WebChimera Plugin](http://www.webchimera.org) (which is highly customizable) for video format support and I could make a fork of WebChimera Player to also fetch subtitles from the OpenSubtitles API. It would practically be a "Popcorn Time" plugin for websites, and I'm sure a lot of web developers would have fun playing with something like this.

I know this is what Feross plans on doing without plugins and that should be the proper course of things knowing that NPAPI support will be ended in late 2015 by Chrome (and maybe FireFox).

But bringing Peerflix to websites with a browser plugin might be the best way to also start seeding through WebRTC and help WebTorrent grow into the future pluginless implementation of this concept. :)

**Comment by yipperr** [comment]
napapi is not supported any longer on new version of chrome so this can't be useful even as a stopgap idea 
i've never heard of ninja video before could u describe how they worked ?
was it a vlc webplugin streaming http stream from different sources or did they have the vlcwebplugin act a player to a torrent client that starts a webserver to stream the data to a player like acestreams ?

**Comment by jaruba** [comment]
I have the chrome installed on both laptop and PC and NPAPIs work without problems. Only Chrome Canary doesn't support NPAPIs, but Chrome Canary is not the official Chrome release, it's the bleeding edge experimental version of Chrome.

I'm unsure of what exactly the website plugin did, but I know it was NPAPI based, they used Divx Web Player and it started a local server that was streaming to the website page.

In about a week or so, maybe sooner, I'll release the plugin I was asking about (as msi and github repo), learned some C++ and started it myself in the meanwhile, made it work, just have to clean up the code and fix some minor bugs.

**Comment by jaruba** [comment]
Ninja Video on NY Times: http://www.nytimes.com/video/technology/100000003133960/ninja-queen-criminal.html

**Comment by jaruba** [comment]
Also, this doesn't need to be an NPAPI in the future when support is stopped, it could simply be a local application that could be called from the web with a registered anchor (like magnet links open the torrent application), only it opens WebChimera in a window with node-webkit.

**Comment by yipperr** [comment]
that was quick thanks for the info

**Comment by jaruba** [comment]
@yipperr Here it is: [Powder NPAPI Plugin](https://github.com/jaruba/PowderNPAPI), keep in mind this is highly experimental atm.

It's a very simple plugin that sends (on request) a JSON Object with data to the browser page. The data in the JSON Object is simply the parsed output that Peerflix normally prints to the command line.

**Comment by yipperr** [comment]
@jaruba  have you considered making it support the linux os the node linux binary and probably include the webchimeraplayer to play from the torrent-stream server also think about using the torrert-stream engine i din't have a look at the api

**Comment by jaruba** [comment]
The plugin is made in C++, as I'm a novice with C++, I wouldn't know if it is possible to embed node.js in it directly. I used Peerflix because it outputs the data from torrent-stream to the command line.

The plugin launches a cmd.exe with Peerflix, parses the output of the command line and sends it to the browser page that requested it.

As of Linux / Mac OS versions, I guess the only difference would be to get the correct paths to the plugin folder and use the correct library to launch and kill terminal processes, as the parsing should be done the same. But I don't have the time to install other OS's and make versions to support them. The code should be easy enough to understand though, everything is in ```src\PowderNPAPIAPI.cpp``` and ```src\PowderNPAPIAPI.h```.

I can make a simple example of it working with WebChimera Player as I've already done tests with it. (I'll try to do this today, shouldn't take long)

**Comment by jaruba** [comment]
Also, a person that knows C++ well and has access to Linux and Mac OS might be able to make versions for them in 1 day. As the plugin itself is very simplistic, Peerflix is doing all the hard lifting.

**Comment by yipperr** [comment]
sure i just wanted to let you there definitely is interest in npapi plugins so it a worthwhile project like you said because peerflix is awesome making it accessible is a good project but you already know this presume on a side note on the asm.js there is a compiled version of lib265.js in javascript 
http://www.libde265.org/blog/2014/04/10/libde265-js-javascript-hevch-265-bitstream-decoder/

its runs a 47 fps on my laptop which is i7  i was searching for something like this

**Comment by jaruba** [comment]
Glad to know you find it useful. :)

Does this demo work for you?

http://jaruba.github.io/PowderNPAPI/webchimera-demo/

This demo is streaming torrents directly on GitHub, that's funny in so many ways! :)))

I added some design elements too, getting bored of the simplistic white page demos.

**Comment by jaruba** [comment]
The link you gave is indeed interesting, but I'm unsure of what video formats it supports. As the last comment implies it did not work for him with .mkv. Also, I guess .avi is out of the question.

For it to work with Peerflix and all torrent sources, it would need to support .mkv and .avi, as .mp4 is supported natively by the browser. 

Also, it seems quite a bit slower then a plugin, on my laptop, which, I have to admit is full of 1000 chrome tabs, photoshop opened, and a lot of other crazy stuff atm, I get about 21 fps, and I can see the frame rendering, while WebChimera (and VLC Web Plugin by association) works great even with full hd sources. So on a performance scale, it clearly slower.

For a wide audience, this might not be the best choice. But if the website visitors need to install Powder Plugin anyway, i guess WebChimera (or any other web player plugin) could be bundled with the package.

**Comment by yipperr** [comment]
@jaruba  it only play hevc bitstream files, the  library cannot parse any containers plugins run c++ code this is javasciprt over the v8 with ahead of time optimizations 
unfortunately my university blocks torrents all through layer3 by blocking udp and by blocking all ports except 80 and 443 where they allow tcp only  only way out a ssl tunnel

**Comment by jaruba** [comment]
Sounds like your university is a great place to hold a hacking marathon. :)

If the *Lord of Time* is generous to me, I'll try reserving some of it to making Linux and Mac OS versions too. But atm, I'm up to my neck in projects for the next few months.

**Comment by yipperr** [comment]
not really all mostly idiots here lol. , the typical study for getting a job bunch they still byheart code to pass by so really not the place you described  
if your interested i was in the process of stripping the hevc bitstream from this hevc file http://psarips.com/wp-content/uploads/2015/03/Transformers.Age_.of_.Extinction.Sample.mkv?_=0
with ffmpeg and play with the library just for fun :)

**Comment by jaruba** [comment]
Sorry, have a lot of work to do today. :)
