### ISSUE TITLE
Chrome integration

### ISSUE THREAD

**Issue by melkir** [mafintosh/peerflix#171]
Is there any way to stream torrent directly from chrome ?
Like we can do with firefox by selecting "Open with Torrent Video Player"
A plugin for example

**Comment by jaruba** [comment]
I mentioned this [here](https://github.com/mafintosh/peerflix/issues/167) too. Since then I've learned a bit of C++ and started working on an NPAPI browser plugin.

I have successfully streamed a torrent  (through Peerflix, playing with WebChimera) in all browsers on a Windows system, but I'd still work a bit more on it (code is still a bit messy). Maybe in about a week I'll package it and also release it as open source on GitHub.

**Comment by mafintosh** [comment]
You can also use this `-w` option that play the video in your browser through peerflix using [webplay](https://github.com/mafintosh/webplay)

**Comment by jaruba** [comment]
I made a simple NPAPI plugin that fetches the Peerflix data from the browser, it currently only accepts info hashes from magnet links.

You can check it out here: [Powder NPAPI Plugin](https://github.com/jaruba/PowderNPAPI)

**Comment by jordansteeves** [comment]
Is anyone working on a PPAPI plugin to play all file types (avi, mkv etc)?

**Comment by jaruba** [comment]
There is no way to make a PPAPI that will play all file types (at least not from VLC), we have discussed this rigorously at WebChimera. PPAPI is pretty much the death of advanced players in the browser.

Firefox will be the only browser that will still support NPAPI from September.

**Comment by Ivshti** [comment]
You might want to check this out https://groups.google.com/forum/#!msg/native-client-discuss/9YULWR9KzO0/UP_Y69quJkEJ

It's not a complete solution, but if libav is available for NaCL, then that's a base for a PPAPI plugin.

It seems that things have to either go in the way of libav or to porting libvlc.

The only advantage of libvlc here is that it's extremely rugged, and packed with plugins for everything. In a real world use case though, few of these features are a deal-breaker, and those that are can be re-implemented on libav.  

Libav has one huge disadvantage however - that it's much lower level than libvlc. So creating such a plugin would be tough.

**Comment by jaruba** [comment]
@Ivshti You really did break your daily schedule, didn't you? :))

**Comment by jordansteeves** [comment]
Is writing a vlc PPAPI plugin not an option?

**Comment by jaruba** [comment]
https://forum.videolan.org/viewtopic.php?f=5&t=107178

This post has recent comments from Jean-Baptiste Kempf (owner and original author of VLC), from my knowledge, no one from the VLC team has began work on a PPAPI plugin, nor plan to in the near future.

@RSATom might know more about it though.

**Comment by jordansteeves** [comment]
Darn! Thanks for the help @jaruba.

**Comment by Ivshti** [comment]
@jordansteeves the problem with VLC is that PPAPI plugins run in something called Native Client, which is indeed an environment where (kind of) native code is ran but heavily sandboxed - think of it as the Dalvik VM for Android.
 
C and C++ code can be compiled to NaCL, but all the environmental changes - the sandboxing, the different compiler - require a significant amount of porting.

libuv is much smaller, architecturally simpler and IMO better maintained. In fact it's one of the many components of VLC. It also minimises use of platform-specific code, which is consistent with the idea of NaCL.

If such a plugin is made libuv will be the way, and VLC is next to impossible - realistically, forget about it.

**Comment by RSATom** [comment]
@ivshty, I think you mean `libav`, not `libuv`. It's totally different things.

**Comment by RSATom** [comment]
https://trac.videolan.org/vlc/ticket/14484

**Comment by Ivshti** [comment]
Oops. mentioned libav 4 times in my previous post and written libuv in the next one. Muscle memory :)

**Comment by RSATom** [comment]
it seems some guy almost managed to get it working: https://forum.videolan.org/viewtopic.php?t=126480
