### ISSUE TITLE
Can't include subtitles with spaces in its file name

### ISSUE THREAD

**Issue by thiagonevesuf** [mafintosh/peerflix#182]
If you try to insert a subtitle with spaces in its name (using -t <subtitle name>), vlc tries to load wrongly and gives an error.
That error doesn't happen if the subtitle name is between quotes.

Example:
It doesn't work:
peerflix Marvels\ Agent\ Carter\ S01E08\ 720p\ HDTV\ x264-IMMERSE\ \[eztv\]\ \[3480848\].torrent --vlc -t Marvels.Agent.Carter.S01E08.720p.HDTV.x264-\ IMMERSE.srt

But, it works:
 peerflix Marvels\ Agent\ Carter\ S01E08\ 720p\ HDTV\ x264-IMMERSE\ \[eztv\]\ \[3480848\].torrent --vlc -t "Marvels.Agent.Carter.S01E08.720p.HDTV.x264-\ IMMERSE.srt"

**Comment by mafintosh** [comment]
Fixed 0.26.1
