### ISSUE TITLE
Cannot continue an interrupted download / Can't stream a magnet

### ISSUE THREAD

**Issue by watdafox** [mafintosh/peerflix#189]
Hello, 

I'm unable to continue an interrupted download and I can't stream from a magnet link (torrent files are ok though); I used to be able to do this.

I think it has something to do with the dependencies, here's why: 

- Doesn't work with recent version
- Doesn't work if I use 22.3 tgz archive
- It works if I use a frozen 22.3 zip archive that I have on my computer, containing every deps installed through 'npm install'.

I tried to isolate the issue in the deps, but I see nothing wrong (and there's like sooooo many of them^^)

**Comment by jaruba** [comment]
"I'm unable to continue an interrupted download" - could you describe this issue a bit more?

I'm wondering if I have the same issue, if I download only 1 file from a torrent with multiple files, then the peer count reaches 0, I can't download anything else from that torrent, because peerflix never searches for new peers when I ```.select()``` or try to stream a new file.

**Comment by watdafox** [comment]
Well, take a torrent that's 1 GB. I only download 50% then stop. I launch the download again to continue to download 51%, 52% etc... but since a few days, this is not working anymore. 

And yes, the peer count can drop to 0 too for me.

**Comment by mafintosh** [comment]
We should probably just reset peer state when it reaches 0 and you don't have any selected files

**Comment by jaruba** [comment]
Is there any way to reset peer state without destroying the engine or closing the streaming server?

**Comment by jaruba** [comment]
I tried adding a new function to torrent-stream:

	engine.discover = function() {
		discovery = peerDiscovery(opts);
		discovery.on('peer', function(addr) {
			if (blocked.contains(addr.split(':')[0])) {
				engine.emit('blocked-peer', addr);
			} else {
				engine.emit('peer', addr);
				engine.connect(addr);
			}
		});
	};

Then I waited for the selected file to finish and the peers to go down to 0. Then selected a new file, and did ```engine.discover()```.

Amazingly it went from peers 0 to 1 and continued downloading very slowly. (doesn't ever increase above 1 though). Is there something wrong with my attempt? Or maybe I need to pass ```opts``` again?

**Comment by jaruba** [comment]
I'm getting the same results if I only use:

	engine.discover = function() {
		return discovery.setTorrent(link);
	};

Only finds 1 peer..

**Comment by jaruba** [comment]
This worked best for me to restart peer discovery:

	engine.discover = function() {
		discovery.stop();
		discovery = peerDiscovery(opts);
		discovery.on('peer', function(addr) {
			if (blocked.contains(addr.split(':')[0])) {
				engine.emit('blocked-peer', addr);
			} else {
				engine.emit('peer', addr);
				engine.connect(addr);
			}
		});
		discovery.setTorrent(link);
	};

I'm sure this isn't the best way to do it, and it only manages to find 3 peers for some reason, but if I restart the engine it gets 19-20 peers.

Does it avoid connecting to peers that have been previously used?

**Comment by watdafox** [comment]
Totally fixed! I just tried with 0.29.2

I don't know if it's peerflix or torrent-stream, but it's working for us at the moment. I'll leave this to the owner to close if it seems fit.

**Comment by mafintosh** [comment]
There was a couple of great improvements in the latest version of torrent-stream by @thermatk so good to hear this seems to fix other issues as well :+1:
