### ISSUE TITLE
Restart the same torrent after .remove and .destroy

### ISSUE THREAD

**Issue by jaruba** [mafintosh/peerflix#190]
I start peerflix with:

    engine = peerflix(magnet)

Then destroy it with:

    engine.remove(function() {
        engine.destroy(function() {
            // some code
        })
    })

But then if I use ```engine = peerflix(magnet)``` again with the same magnet or torrent link, everything seems to work fine, it downloads it, but the streaming link it gives me is inaccessible. Is this a problem with ```.destroy()``` or am I doing something wrong?

**Comment by mafintosh** [comment]
I think currently you need to call `engine.server.close()` as well. Could you try and see if that works? If so we should do that automatically

**Comment by jaruba** [comment]
Yes, that fixes it entirely. Thank you. :)

Could you also please tell me if it's possible to call ```peerflix()``` with arguments at this current point of the project?

**Comment by jaruba** [comment]
It seems this wasn't fixed as I thought, the problem is with ``rimraf`` in ``engine.remove()``. If I do:

    powGlobals.engine.server.close(function() {
        powGlobals.engine.remove(function(err) {
            console.log(err);
            powGlobals.engine.destroy();
        })
    })

I get:

    Error: ENOTEMPTY: directory not empty, rmdir

Looking in the download folder, I see all the files have been removed except the video file (that the http server was streaming).

Is it possible that the server did not close, or did not close before the callback function was called? Which may be blocking the deletion of the video file?

If I do ``engine = peerflix(magnet)`` on the same magnet (which did not remove the video correctly before) it then downloads it from the start correctly, but streaming does not work (tested the link with VLC).

Any thoughts or hints about this?

**Comment by jaruba** [comment]
Increasing the maximum number of attempts to delete these files in ``rimraf`` fixes the issue for me.

Created a PR for ``torrent-stream``: https://github.com/mafintosh/torrent-stream/pull/119

**Comment by mafintosh** [comment]
This was fixed in torrent-stream 0.19.1 (by you!) so if you reinstall peerflix this should be fixed
