### ISSUE TITLE
3-4 files created in temp dir but just need one ... ?

### ISSUE THREAD

**Issue by smolleyes** [mafintosh/peerflix#191]
hi

i start my streaming with

videoStreamer = peerflix(torrent.info, {
                    connections: 100,
                    path: tmpFolder,
                    index: id
                });

my app stream to good file BUT before starting it freeze my app few seconds on torrents with multiples avi files for exemple and in my temp dir i don t have only the file i selected, i have 3 or 4 folders created with their files... so i think the space allocation time of this files is the problem

any idear how to fix this ? 

thanks

**Comment by jaruba** [comment]
I think that happens because of ```.torrent.pieceLength```, peerflix downloads in pieces and all the pieces (except the last one) have the same byte length.

When you download a file, the first and last parts of that file are downloaded first, and those particular pieces might contain parts of the previous and the next file in the torrent, so those files are created too, although only a very small part of them was downloaded.

**Comment by jaruba** [comment]
To understand this better, in a visual environment, you can check out [the app I posted](https://github.com/jaruba/PowderPlayer) last night, when in video streaming mode, right click and go to "Torrent Data" and you will be presented with the Torrent Client User Interface.

You can see that the files before and after the file that is selected are also downloaded (but only about 3% of them), if the files are very small, like text files, etc, it will be fully downloaded as they are part of that piece's length entirely.

This is normal behavior for Peerflix, I don't think this is a bug or can be fixed.

**Comment by smolleyes** [comment]
hello jaruba :)

you re everywhere !! 

thanks for the explanation good to know ! 

i ll test you app asap, congratulations for that :)

**Comment by jaruba** [comment]
Lol, yeah, I get around. One small question though, does the code you posted work for you?

    videoStreamer = peerflix(torrent.info, {
        connections: 100,
        path: tmpFolder,
        index: id
    });

any param ("connections", "tmp", "path", ...) I try to add this way when calling peerflix seems to be ignored.

**Comment by smolleyes** [comment]
ah yeah everything works, path is respected and index too :)

**Comment by jaruba** [comment]
strange, maybe I need to update peerflix in my app :)

**Comment by smolleyes** [comment]
maybe, i modified some few things in peerflix or use the one of popcorn time :p
