### ISSUE TITLE
peerflix download torrent file to memory no temp

### ISSUE THREAD

**Issue by smed79** [mafintosh/peerflix#195]
Hello, 
is that peerflix have an "cache option" to download the torrent file to memory without saving file to disk?

If not, consider this a request :-)

Best regards, 
Med

**Comment by SMed79** [comment]
That's manually how I do : 

**Free RAM**
```sudo sysctl -w vm.drop_caches=3 > /dev/null```

**Creat RAM disck**
```sudo mkdir /run/media/med/RAM```

**Mount RAM disck**
```sudo mount -t tmpfs -o size=2048m tmpfs /run/media/med/RAM```

**Usage**
```peerflix magnet-link --vlc -f /run/media/med/RAM```

or
**alias** on **.bashrc** (VLC as defaut player)

```alias peerflix2ram='echo "# RAM memory usage:" && free -m && sudo sysctl -w vm.drop_caches=3 > /dev/null && echo "# RAM memory usage after clean up:" && free -m && 'echo "# Creat RAM disck mount folder:" && sudo mkdir /run/media/med/RAM && echo "# mount RAM disck folder:" && sudo mount -t tmpfs -o size=2048m tmpfs /run/media/med/RAM && peerflix --vlc -f /run/media/med/RAM'```

**Usage** 
```peerflix2ram magnet-link```

Hope this helps some one ...

* "**med**" is my user profile.
* "**2048m**" is size for my created RAM disck
* "**OS**" [Manjaro Linux](https://manjaro.github.io/) (Arch Linux)

**Comment by watdafox** [comment]
webtorrent does that entirely in ram

**Comment by feross** [comment]
Heh, but that's a bug. :-) WebTorrent is writing to disk too, but somehow
still holding onto the memory.

**Comment by watdafox** [comment]
hahaha, didn't know that, thought it was just a wierd behavior by choice
