### ISSUE TITLE
Peerflix stopped working

### ISSUE THREAD

**Issue by mohitathwani** [mafintosh/peerflix#199]
For some weird reason, perplex has stopped working for me since just now ..
The error is 
```events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EACCES, open '/tmp/torrent-stream/4c09cbf638a45c001a3e91b3bf0b728cbe8d2203.torrent'
    at Error (native)
```

I updated the version of node on my system to the latest version and even re-installed peerflix ... no luck :(

**Comment by jaruba** [comment]
could it be related to this:

http://stackoverflow.com/questions/9164915/node-js-eacces-error-when-listening-on-most-ports

try running node as root and see what happens.

**Comment by mohitathwani** [comment]
I don't think it's a sudo problem because it's been working fine without sudo for over a month. However, it seems I have solved the issue after completely deleting the peerflix directory, updating my version of nodejs, and reinstalling peerflix.

**Comment by mafintosh** [comment]
@mohitathwani try removing `/tmp/torrent-stream` and try again? also do you have write access to `/tmp/` in general?

**Comment by mohitathwani** [comment]
Yeah I did delete that directory and yes I do have write permissions to /tmp/. 

I think deleting everything and reinstalling again seems to have solved the issue. 



—
Mohit  Athwani http://about.me/mohitathwani
