### ISSUE TITLE
Atom Electron support?

### ISSUE THREAD

**Issue by iadj** [mafintosh/peerflix#213]
I'm trying to get Peerflix to work in Atom Electron. The code shown below doesn't appear to work. I was wondering if it's possible to get peerflix working with Electron?

	mainWindow.webContents.on('did-finish-load', function() {
		var engine = peerflix(MagnetURL);

		engine.on('ready', function() {
			console.log("Ready");
			mainWindow.webContents.send('stream', 'Ready');
		  console.log(engine.files); // the files
		  engine.server.listen(8888); // start the http server
		});`

**Comment by jaruba** [comment]
> I'm trying to get Peerflix to work in Atom Electron.

``peerflix`` already works with Electron. [Playback](https://github.com/mafintosh/playback) is made in Electron and it uses ``torrent-stream``.

> The code shown below doesn't appear to work.

Can you elaborate on this? What error are you getting? Did you also add:

    var peerflix = require('peerflix');

as a global variable somewhere in your code before doing:

    var engine = peerflix(MagnetURL);

?

**Comment by iadj** [comment]
@jaruba I did include the peerflix requirement.
Nothing appears to happen. When I load a torrent with 2 files, console returns the following twice:

`[{deselect: [Function], select: [Function], createReadStream: [Function]}]` 

When I run peerflix directly from the command line, I'm asked to open a port and am instantly able to access the streaming video, but when testing the Electron app, the server doesn't appear to start listening on port 8888 (neither does it return file names, but the above quoted line).

**Comment by jaruba** [comment]
[{deselect: [Function], select: [Function], createReadStream: [Function]}]

this is the response for this line:

    console.log(engine.files);

Try changing this line with:

    console.log(engine.files[0]);

and tell me what the console log says.

**Comment by iadj** [comment]
`console.log(engine.files[0]);` also returns `[{deselect: [Function], select: [Function], createReadStream: [Function]}] `

**Comment by jaruba** [comment]
uhm.. strange.. let's go back to your code for a second.. Change all this code:

    engine.on('ready', function() {
        console.log("Ready");
        mainWindow.webContents.send('stream', 'Ready');
      console.log(engine.files); // the files
      engine.server.listen(8888); // start the http server
    });

to this:

    engine.server.on('listening', function() {
        var myLink = 'http://localhost:' + engine.server.address().port + '/';
        console.log(myLink);
    });

and tell me what your console log says.

**Comment by iadj** [comment]
`http://localhost:59007/`

Visiting the link also seems to start the download for a 1.5GB AVI file (I assume that's the metadata from the torrent)

**Comment by jaruba** [comment]
no.. that's the streaming link.. put that in VLC and it will play the largest video file from the torrent.

**Comment by iadj** [comment]
Ah I see, awesome. Thanks! Is there any major difference between `engine.server.on('ready', function() {` and `engine.server.on('listening', function() {` except for the port being automatically set?

**Comment by jaruba** [comment]
> ``engine.on('ready', fn)``
> Emitted when the engine is ready to be used. The files array will be empty until this event is emitted

ie: when ``torrent-stream`` is ready to be used

> ``engine.server.on('listening',fn)``

Emitted when the streaming server has started listening for incoming connections (players)

**Comment by jaruba** [comment]
> except for the port being automatically set

none of those events let you set the port to the streaming server, to set the port for the streaming server you'd need to use:

    var engine = peerflix(MagnetURL,{ port: 9999 });

which would set the streaming server port to ``9999`` when it will be created.
