### ISSUE TITLE
How to stream torrent to a video tag existent in an NW.js application ?

### ISSUE THREAD

**Issue by saru95** [mafintosh/peerflix#214]
I have a NW.js application with a video tag. How would I go about streaming to it using peerflix ? Can I bypass some CLI flags and use "childProcess" to run it within ?

**Comment by jaruba** [comment]
- ``npm install peerflix``

- getting the streaming link example code: https://github.com/mafintosh/peerflix/issues/211#issuecomment-116320318

- read the ``torrent-stream`` API docs: https://github.com/mafintosh/torrent-stream/blob/master/README.md#full-api

- don't use video tag, check out ``WebChimera.js`` instead: http://wiki.webchimera.org/WebChimera.js

**Comment by saru95** [comment]
Isn't web chimera going to get deprecated ?

**Comment by jaruba** [comment]
``WebChimera.js`` is a special branch from WebChimera made specifically for NW.js and Electron developers, it uses the native Node.js environment to accomplish playback, not an NPAPI Plugin, so it cannot become deprecated.

**Comment by saru95** [comment]
Also, can you help me on how to feed webchimera player the torrent stream ?

**Comment by jaruba** [comment]
*HTML*

    <div id="player"></div>

*JS*

    var peerflix = require('peerflix'),
        engine = peerflix(magnetLink),
        wjs = require("wcjs-player"),
        player = new wjs("#player").addPlayer({ autoplay: true });
    
    engine.server.on('listening', function() {
        var myLink = 'http://localhost:' + engine.server.address().port + '/';
        player.addPlaylist(myLink);
    });

[WebChimera.js API Docs](https://github.com/jaruba/wcjs-player/wiki/JavaScript-API)

**Comment by saru95** [comment]
Thanks a tonn man !

**Comment by amilajack** [comment]
@jaruba I'm getting the following error:

```
Cannot resolve module 'webchimera.js
```

**Comment by jaruba** [comment]
@amilajack try using [wcjs-prebuilt](https://github.com/Ivshti/wcjs-prebuilt) and load the player as described in [this comment](https://github.com/jaruba/wcjs-player/issues/33#issuecomment-180796556)
