### ISSUE TITLE
Peerflix doesn't kill streaming server on engine.destroy()

### ISSUE THREAD

**Issue by iadj** [mafintosh/peerflix#215]
I have the following function, which is called every time a magnet is loaded into my peerflix app. It should kill the previous peerflix engine whenever a new 'engine' is created.
playStep1 returns the callback when I start a new playback instance, but it doesn't appear to actually destroy the streaming server (http://localhost:port). 

    var peerflix = require('peerflix');
    var Q = require('q');

    function(magnet){
	//Step 1: Check if a torrent is streaming. If so, destroy the stream.
		function playStep1(){
			if(GLOBAL.engine !== undefined){
				engine.destroy(function(){
					console.log('Destroy');
				});
			}
		}

		//Step 2: Start up new torrent stream
		function playStep2(){
			GLOBAL.engine  = peerflix(magnet);
		}

		//Step 3: When torrent stream is available, add it to GLOBAL.magnets array
		function playStep3(){
			engine.server.on('listening', function() {
				GLOBAL.magnets[streamCount] = magnet;
			});
		}

		//Up the streamCount so the next magnet link can get saved in GLOBAL.magnets[streamCount]
			function playStep4(){
				streamCount++;
			}

		Q.fcall(playStep1)
		.then(playStep2)
		.then(playStep3)
		.then(playStep4)
		.catch(function(error){
			console.log(error);
		})
		.done();
    }

**Comment by jaruba** [comment]
> I think currently you need to call engine.server.close() as well. Could you try and see if that works? If so we should do that automatically

quoted @mafintosh from this comment: https://github.com/mafintosh/peerflix/issues/190#issuecomment-77683863

**Comment by iadj** [comment]
@jaruba I tried the way you described in the referenced thread and it indeed closes the server when called without `Q` promises. However doing this without promises kills the next `engine` created in `playStep2`.

When I chain the process (to make sure the new `engine` creates when the previous one is destroyed), `playStep1` never returns 'Destroyed':

	function playStep1(){
        var deferred = Q.defer();
        engine.server.close(function() {
      		 engine.destroy(function(){
                         console.log('Destroyed');
                         deferred.resolve();
                    });
         });
          return deferred.promise;
	 }

**Comment by jaruba** [comment]
could you throw some ``console.log()``'s in there to see which event callback function isn't triggered?

**Comment by iadj** [comment]
@jaruba When I `console.log()`, everything before `engine.server.close` is logged. Nothing after. I can also properly return `engine.server.address().port`, so `engine` should be properly defined.

**Comment by jaruba** [comment]
Yeah, just realised it was a dumb question, only ``server.close`` could of been the issue. :)

What is your streaming server doing? If it is in use when you try to close it (ie: streaming to something), then it will not close until it is released by all current clients.

**Comment by iadj** [comment]
@jaruba That was it it! My client isn't closing the stream URL. Thank you @jaruba for the insight :100: 

It would be nice to have a 'force' option for `engine.server.close`, to force closing the stream even if it's open in client.

**Comment by jaruba** [comment]
It would indeed be nice.. ``peerflix`` uses [http.Server](https://nodejs.org/api/http.html#http_class_http_server) to create the server.

From the docs:

> ``server.close([callback])#``
> Stops the server from accepting new connections and keeps existing connections. This function is asynchronous, the server is finally closed when all connections are ended and the server emits a 'close' event. Optionally, you can pass a callback to listen for the 'close' event. If present, the callback is invoked with any potential error as the first and only argument.

Looking at the docs, you can see there is no way of closing any connection to a client from the server-side.

More so, everything in the ``http.Server`` API seems to only affect future clients, even setting the server timeout would not disconnect or change the timeout setting of already connected users.

**Comment by iadj** [comment]
@jaruba If I `engine.server.close`, but not `engine.destroy()` does peerflix basically become torrent-stream with the torrent continuing to stream (except not to the `http.Server`)?

**Comment by jaruba** [comment]
> continuing to stream

You mean "continuing to download"? Yeah, it should continue to download the files normally, just doesn't use a server to stream the files.

**Comment by jaruba** [comment]
@iadj Apparently there is a way to close the connections from the server side, it's just not developer friendly:

http://stackoverflow.com/questions/18874689/force-close-all-connections-in-a-node-js-http-server#answer-18875088
