### ISSUE TITLE
How to play online streams from http://torrent-tv.ru/

### ISSUE THREAD

**Issue by vmmelnic** [mafintosh/peerflix#218]
Hi folks,

I am a one of that lucky who have installed and configured this powerful feature on my own Wi-Fi router and now I want to continue in my tests and I'm gonna to play online torrent streams from http://torrent-tv.ru/ (or similar). What do you think, is it possible?

**Comment by mafintosh** [comment]
peerflix supports playback of all regular torrent files and magnet links

**Comment by Ivshti** [comment]
Great question, even though it's off-topic.

Look at torrent-tv.ru's guide on how to use on Mac, they have a HTTP proxy software you can download and run. They use Ace Stream, who have extended the bittorrent protocol to support live playing.

As I said, Ace Stream have a HTTP proxy, so this can be used on other platforms / through other software, but unfortunately it will remain proprietary until someone reverse engineers it.

**Comment by vmmelnic** [comment]
They software are virus, and works unstable, it's hardcoded to some specific hardware, and there are a lots of other issues, but I need only open their torrent streams in peerflix. I've tried to do it, but I see only
```bash
fetching torrent metadata from 0 peers
```
