### ISSUE TITLE
[Issue] TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by jounlye** [mafintosh/peerflix#221]
Hi guys ! :smiley: 
I have just installed peerflix with nodejs and npm.
The problem is when I type the basic command to use with vlc, I get this error : 
                                                         -------------------
C:\Users\sjboy>peerflix "C:\Users\sjboy\Downloads\J'irai.dormir.chez.vous-S06E02-Uruguay-09.07.2015.torrent" --vlc
C:\Users\sjboy\AppData\Roaming\npm\node_modules\peerflix\app.js:223
        var vlcPath = key['InstallDir'].value + path.sep + 'vlc'
                                       ^
TypeError: Cannot read property 'value' of undefined
    at Server.<anonymous> (C:\Users\sjboy\AppData\Roaming\npm\node_modules\peerflix\app.js:223:40)
    at Server.emit (events.js:104:17)
    at net.js:1171:12
    at process._tickCallback (node.js:355:11)
                                                         -------------------

So, I ask you to help me to fix this problem. 
Thanks !

**Comment by jaruba** [comment]
Are you using a 32bit or 64bit OS?

Open a command line and run ``regedit``, now check for the paths from the registry that match the ``registry()`` calls from these lines: https://github.com/mafintosh/peerflix/blob/master/app.js#L204-L220

Tell me if you find VLC anywhere in your registry and what the registry path to it is.

**Comment by jounlye** [comment]
I'm using the 64bit version of Windows 10.

The path to VLC in the registry that I've found is the following : registry('HKLM/Software/VideoLAN/VLC')

**Comment by jaruba** [comment]
could you edit ``app.js`` and add ``key = registry('HKLM/Software/VideoLAN/VLC')`` right before the line with the error (line 223) and see if the error persists?

**Comment by jounlye** [comment]
Should I write it like this : 

if (key) {
  key = registry('HKLM/Software/VideoLAN/VLC')
 var vlcPath = key['InstallDir'].value + path.sep + 'vlc'
        VLC_ARGS = VLC_ARGS.split(' ')
        VLC_ARGS.unshift(localHref)
        proc.execFile(vlcPath, VLC_ARGS)

**Comment by jaruba** [comment]
Yeah, just to force getting that specific path from the registry, this will tell us if it's loading the wrong registry path or if it's some compatibility issue between [windows-no-runnable](https://github.com/Benvie/node-Windows) (that used to access the registry) and Windows 10.

**Comment by jounlye** [comment]
Thank you so much @jaruba, the issue is fixed  !  :clap:

**Comment by jaruba** [comment]
Could you please check if ``HKLM/Software/Wow6432Node/VideoLAN/VLC`` is available in the registry too? As this would still need to be fixed in ``peerflix`` for other users too.

**Comment by jounlye** [comment]
I have already checked this path and for me, there's no VideoLAN folder in HKLM/Software/Wow6432Node

**Comment by jaruba** [comment]
Interesting, thanks. :)

**Comment by jaruba** [comment]
Could you please help me with one more test (that could fix it for all users), remove the line you added before (``key = registry('HKLM/Software/VideoLAN/VLC')``) then remove all these lines: https://github.com/mafintosh/peerflix/blob/master/app.js#L204-L220

and add these lines instead of them:

    key = registry('HKLM/Software/Wow6432Node/VideoLAN/VLC')
    if (!key['InstallDir']) {
        key = registry('HKLM/Software/VideoLAN/VLC') 
        if (!key['InstallDir']) key = undefined;
    }

**Comment by jounlye** [comment]
Ok, wait few seconds :)

**Comment by jounlye** [comment]
![image](https://cloud.githubusercontent.com/assets/13719987/9261016/909bcad4-420b-11e5-9ce3-4faac6495cdf.png)
Should I do it like this?

**Comment by jounlye** [comment]
Alright, I have just tested peerflix command with a torrent and it works, great job ! :smile:

**Comment by jaruba** [comment]
@mafintosh

It seems that ``registry()`` from ``windows-no-runnable`` does not give any error to ``catch``, do you think this change is safe? Should I make a PR?

**Comment by gearlles** [comment]
Got the same error using Windows 10 64bit. VLC is located at `HKLM/Software/VideoLAN/VLC` in registry and [this](https://github.com/mafintosh/peerflix/issues/221#issuecomment-129259149) solved the problem. Any plans to release the fix?
