### ISSUE TITLE
Peerflix stuck on loading torrent

### ISSUE THREAD

**Issue by jakeelwes** [mafintosh/peerflix#233]
Hey, I seem to have successfully installed peerflix 0.31.0 on my macbook (osx10.10.3), although it does nothing when I put in 'peerflix "magnet_link" -v', just gets stuck on that command and doesn't load the peerflix interface. It used to work fine on my computer and not too sure whats changed as it was all working before (on the network I'm on) I have had to add a 802.1X config profile for my school but its inactive when using peerflix at home, this couldn't interfere could it? 
I've updated node.js and when reinstalling peerflix I did get one warning:
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"v0.10.26","npm":"1.4.3"})
I now this is a bit vague but any ideas what I might be doing wrong? Thanks

**Comment by shime** [comment]
What's the specific error you're getting? What are you trying to run and what arguments are you providing?

**Comment by niemal** [comment]
This seems exactly like https://github.com/mafintosh/peerflix/issues/259.
Could you please try a different variety of magnet links? i.e. different trackers and/or type of content.

**Comment by jakeelwes** [comment]
Hey thanks for your replies. It's working again, not quite sure what changed. Think it might have been my internet setup in the US, fine now I'm back in the UK.

**Comment by jaruba** [comment]
@jakeelwes awesome, can you close the issue please?
