### ISSUE TITLE
peerflix won't set up

### ISSUE THREAD

**Issue by vitaliy101** [mafintosh/peerflix#247]
so when i type in the command: npm install -g peerflix
i get this:

npm ERR! tar.unpack untar error /Users/Boggyyfresh/.npm/peerflix/0.32.2/package.tgz
npm ERR! Darwin 12.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "peerflix"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! path /usr/local/lib/node_modules/peerflix
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/peerflix'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/peerflix']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/peerflix',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/peerflix',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Boggyyfresh/npm-debug.log

can anyone show me how to resolve this? thanks

**Comment by three17design** [comment]
Try running it with admin permissions:

sudo npm install -g peerflix

**Comment by linuz90** [comment]
I had roughly the same problem of @vitaliy101. I trying installing with sudo and now I get this:

```shell
WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"4.3.1","npm":"2.14.12"})
/usr/local/bin/peerflix -> /usr/local/lib/node_modules/peerflix/app.js
peerflix@0.32.4 /usr/local/lib/node_modules/peerflix
├── keypress@0.2.1
├── clivas@0.1.4
├── network-address@0.0.5
├── range-parser@1.0.3
├── open@0.0.5
├── xtend@4.0.1
├── mime@1.3.4
├── windows-no-runnable@0.0.6
├── rc@0.4.0 (strip-json-comments@0.1.3, deep-extend@0.2.11, ini@1.1.0, minimist@0.0.10)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── numeral@1.5.3
├── pump@0.3.5 (once@1.2.0, end-of-stream@1.0.0)
├── parse-torrent@5.7.1 (get-stdin@5.0.1, blob-to-buffer@1.2.6, simple-get@2.0.0, magnet-uri@5.1.3, parse-torrent-file@3.3.2)
├── inquirer@0.8.5 (ansi-regex@1.1.1, figures@1.4.0, through@2.3.8, cli-width@1.1.1, readline2@0.1.1, chalk@1.1.1, lodash@3.10.1, rx@2.5.3)
├── airplay-js@0.2.16 (mdns-js@0.5.0, plist@1.2.0)
└── torrent-stream@1.0.2 (bitfield@0.1.0, immediate-chunk-store@1.0.8, hat@0.0.3, torrent-piece@1.0.0, bncode@0.5.3, mkdirp@0.3.5, end-of-stream@0.1.5, ip-set@1.0.0, parse-torrent@4.1.0, peer-wire-swarm@0.12.1, rimraf@2.5.2, torrent-discovery@5.3.2, fs-chunk-store@1.3.5)
```

What's the problem? Thanks a lot!

**Comment by mafintosh** [comment]
@linuz90 looked like it installed fine to me?

**Comment by linuz90** [comment]
Oh sorry, it wasn't working while I was posting that, and now it's working. By the way maybe you could consider adding the "sudo" part for El Capitan users in the readme. Thanks anyway for the quick reply!

**Comment by mafintosh** [comment]
@linuz90 i'll add a mention about using sudo when seeing EACCES error
