### ISSUE TITLE
Feature request: add files from same torrent to queue or select download order

### ISSUE THREAD

**Issue by tsoernes** [mafintosh/peerflix#249]
It would be nice to be able to either
a) Be able to other files from the same torrent to a download queue when streaming a file
and/or
b) Select multiple files to be downloaded and their order

Thanks

**Comment by mafintosh** [comment]
You can use the `-a` flag to add all files to a playlist.

**Comment by joshterrill** [comment]
There is also peerflix-server which can be installed by `npm install -g perrflix-server` which shows a visual of what files are in the torrent, and allows you to tick a checkbox for which ones you want downloaded. Obviously it just extends what peerflix already does, but for some, using a GUI is preferable.
