### ISSUE TITLE
Peerflix OS X Mavericks (10.9.x)

### ISSUE THREAD

**Issue by luispp16** [mafintosh/peerflix#265]
Hi, I'm having troubles installing peerflix on my MBP 13" late-2011. I had already installed the xcode command line tool. I even installed xcode just to be sure and still the issue.

I was doing this:
xcode-select --install
npm install -g peerflix.

I do know how to use peerflix, I was using it in my El Capitan partition, but now in Mavericks it doesn't work.

Any help is well received.
Thanks

**Comment by jaruba** [comment]
Peerflix doesn't have any build prerequisites (except `npm`), so you should be able to install it even without xcode.

Do you see any errors in the installation process?

**Comment by luispp16** [comment]
@jaruba This is the only "error" that the terminal shows -> -bash: npm: command not found.

**Comment by jaruba** [comment]
Download and install `node.js`: https://nodejs.org/en/download/

After your done do:
`npm install -g peerflix`
_in the terminal_

**Comment by luispp16** [comment]
I installed `node.js`, succesfully, but peerflix not so much. This is what terminal shows:

npm ERR! tar.unpack untar error /Users/luispepe/.npm/peerflix/0.32.4/package.tgz
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "peerflix"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path /usr/local/lib/node_modules/peerflix
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/peerflix'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/peerflix']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules/peerflix',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/peerflix',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:35:25',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luispepe/npm-debug.log

![sin titulo](https://cloud.githubusercontent.com/assets/14917136/13466134/d8e5e1dc-e06a-11e5-857a-1321d4e1478b.png)

**Comment by jaruba** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by jaruba** [comment]
or just do: `sudo npm install peerflix -g`

**Comment by luispp16** [comment]
@jaruba The doc explaination worked perfectly. Thanks so much!

**Comment by jaruba** [comment]
no problem, please remember to close the ticket :)
