### ISSUE TITLE
It's possible select a specific file name into a torrent for download?

### ISSUE THREAD

**Issue by fixfluxservices** [mafintosh/peerflix#269]
Hello all, i am a Brazilian developer and i'm using the Peerflix to make a streaming platform.
I need that select an individual specific file to start downloading inside a torrent.
It's possible?

I need to do this with a direct command terminal.
Sorry, i'm learning English.

**Comment by mafintosh** [comment]
yes it is. use the -i or -l options to select a file

**Comment by fixfluxservices** [comment]
Thank you!
Moments before I found the line ".alias ('i', 'index'). describe ('i', 'changed streamed file (index)')" HUEHUEHUE

**Comment by mafintosh** [comment]
glad you figured it out :)
