### ISSUE TITLE
Start peerflix + vlc from nw.js

### ISSUE THREAD

**Issue by webkitten** [mafintosh/peerflix#272]
I'm developing app on nw.js, for start peerflix + vlc i do

`var exec = require('child_process').exec, child;
child = exec(nwDir + '\\nw.exe '+ nwDir +'\\peerflix\\app.js "' + link + '" -v -- --meta-title "' + theTitle + '"');`

Is there another way to do this? (if i will use peerflix as module)

**Comment by jaruba** [comment]
You can include `peerflix` as a node.js module to get the streaming URL, see: https://github.com/mafintosh/peerflix/issues/211#issuecomment-116320318 

Then you can either start a child process with VLC and the streaming URL, or maybe generate a playlist file with all the streaming URLs and start that.

Or maybe you want to play it directly in NW.js, in which case you'll need to rebuild NW.js with full video support, so you can play the streaming URL with the `<video>` tag directly.

An alternative to rebuilding NW.js with full video support is using [WebChimera.js](https://github.com/RSATom/WebChimera.js), and either create your own player or use an already built player ([WebChimera.js Player](https://github.com/jaruba/wcjs-player)). As `WebChimera.js` uses libVLC internally, it will support any media that VLC would.

**Comment by webkitten** [comment]
i do not want to add some player to my nw.js app for playing video, because it takes a lot of space, and start the builded project takes a lot of time(for windows). 

So, i give a choise for users, where play video (now it powder player with powder remote and vlc that do not closes the download server on close).  

I want to find the way how to close server when vlc close)

**Comment by jaruba** [comment]
I think your right, there might be an issue in the code, look here:

https://github.com/mafintosh/peerflix/blob/cfeb0bd54966351edefa1225a04ab01a4b5b9878/app.js#L225-L230

and here:

https://github.com/mafintosh/peerflix/blob/cfeb0bd54966351edefa1225a04ab01a4b5b9878/app.js#L252-L265

It seems that it's listening to the `exit` event on OSX, but not on Windows. Can you try adding the `exit` event to windows too?

**Comment by webkitten** [comment]
yes, it works! Thank you!)
` var vlc = proc.execFile(vlcPath, VLC_ARGS)`
`vlc.on('exit', function () {`
  `if (!argv.n && argv.quit !== false) process.exit(0)`
`})`

**Comment by jaruba** [comment]
@mafintosh This looks like it's simply missing from the code because someone forgot to add it. Can you or @webkitten push it to the project.

I'm still using my `peerflix` fork in some projects, so I can't. :)
