### ISSUE TITLE
Exits without error if subtitles given

### ISSUE THREAD

**Issue by iovis** [mafintosh/peerflix#274]
From 0.33.0 (0.32.4 works fine) if you pass a subtitles file it exits without downloading anything and without giving errors. 

Node version 5.11.0.

**Comment by oomathias** [comment]
in app.js changing
```js
VLC_ARGS += ' --sub-file=' + (process.platform === 'win32') ? argv.t : enc(argv.t)
```
into
```js
VLC_ARGS += ' --sub-file=' + ((process.platform === 'win32') ? argv.t : enc(argv.t))
```
fix the problem.

should I make a pull request?

**Comment by iovis9** [comment]
Sure :)
