### ISSUE TITLE
writeBuffer error

### ISSUE THREAD

**Issue by same31** [mafintosh/peerflix#290]
Hi,

I'm having an issue with peerflix, the download starts fine but at some point the program exits with this error:

```
fs.js:632
    return binding.writeBuffer(fd, buffer, offset, length, position, req);
                   ^

RangeError: offset out of bounds
    at RangeError (native)
    at Object.fs.write (fs.js:632:20)
    at onwrite (/usr/local/lib/node_modules/peerflix/node_modules/torrent-stream/node_modules/fs-chunk-store/node_modules/random-access-file/index.js:110:8)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:619:5)
```

I edited the index file in random-access-file to log a bit more info:

at line 110, fs.write(self.fd, buf, buf.length - offset, length, offset, onwrite), I noticed the result of buf.length - offset is negative.

Any idea why is this happening ?
I am not sure if this issue is due to peerflix, torrent-stream, immediate-chunk-store, fs-chunk-store or random-access-file so I'm posting the issue here.

I tried to download a 2.2Gb video file with peerflix installed on a NAS Synology.

Thank you

**Comment by jaruba** [comment]
This is just a shot in the dark.. but what if none of those modules have any issues and you just tried to download a file that exceeds the maximum file size for the file system that you are using? (maybe you formatted to FAT16 or some crazy thing like that which only supports 2GB max per file)

**Comment by same31** [comment]
Hi jaruba,

My file system is ext4 so this should not be the issue.

**Comment by same31** [comment]
This issue appears on a node 4.2.6 install, it is the most recent version for Synology system.

I installed debian chroot and compiled node 4.5.0 in this environment and the issue did not happen.

**Comment by mafintosh** [comment]
should be fixed if you reinstall peerflix. if not please reopen this issue :)
