### ISSUE TITLE
After npm install getting "SyntaxError: Use of const in strict mode."

### ISSUE THREAD

**Issue by rziegler72** [mafintosh/peerflix#316]
I'm running Ubuntu 14.04, trying to install peerflix for use with vlc.  After installing with "npm install -g peerflix", I'm getting this error from the command line doing anything, even displaying the --help page.

Let me know what additional info I can provide for troubleshooting.

$ peerflix --help

/usr/lib/node_modules/peerflix/node_modules/torrent-stream/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/simple-get/node_modules/unzip-response/index.js:2
const PassThrough = require('stream').PassThrough;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/peerflix/node_modules/torrent-stream/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/simple-get/index.js:8:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by mafintosh** [comment]
I think this is one of @feross' modules so maybe he knows more

**Comment by feross** [comment]
@mafintosh Actually `unzip-response` is a sindre module: https://www.npmjs.com/package/unzip-response

**Comment by mafintosh** [comment]
@feross ah thanks for the quick reply :)
@rziegler72 in that case, which node version are you on?

**Comment by feross** [comment]
It's getting harder and harder to avoid ES6 creeping into modules... I expect he's running Node 0.10.

@rziegler72 - Can you try upgrading to a newer version of Node.js?

Run this:

```bash
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

(You can confirm this is the correct command here: https://github.com/nodesource/distributions#installation-instructions)

After that, it should work!

**Comment by rziegler72** [comment]
"node --version" currently shows v0.10.37.  After running the curl and apt-get, it now shows v6.10.2 and I am now able to run peerflix --help and peerflix --vlc with URLs.

Thanks for the quick responses everyone!

**Comment by feross** [comment]
Glad you got it figured out.
