### ISSUE TITLE
Transmission and Peerflix

### ISSUE THREAD

**Issue by nemanjan00** [mafintosh/peerflix#330]
Hi, 

My routine is to download torrent with whole season (which I have legal access to, ofc) using transmission... 

At the same time, I watch episode from time to time using peerflix... 

I was wondering if there was a way for peerflix to download from transmission since it probbably has some data. 

Tried to use ``-e localhost:51413`` and it did not help...

**Comment by mafintosh** [comment]
you could prob use --path to point to the folder where transmission stores data.

**Comment by nemanjan00** [comment]
Not while it is downloading?
