### ISSUE TITLE
Please help, can't install peerflix

### ISSUE THREAD

**Issue by againpino** [mafintosh/peerflix#333]
So, when i type "sudo npm install -g peerflix" this is what I get
/usr/local/bin/peerflix -> /usr/local/lib/node_modules/peerflix/app.js

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/peerflix/node_modules/spawn-sync
> node postinstall

sh: 1: node: not found
/usr/local/lib
└── (empty)

npm ERR! Linux 4.10.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "peerflix"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs spawn-sync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fabio/npm-debug.log
npm ERR! code 1

**Comment by vitaminace33** [comment]
Have you solved the problem? I have the same one with an up-to-date installation.
```
npm WARN deprecated parse-torrent-file@2.1.4: Use the parse-torrent package instead
/usr/local/bin/peerflix -> /usr/local/lib/node_modules/peerflix/app.js

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/peerflix/node_modules/spawn-sync
> node postinstall

module.js:549
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/peerflix/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
/usr/local/lib
└── (empty)

npm ERR! Linux 4.15.0-22-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "peerflix"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
```

**Comment by againpino** [comment]
Nope. sorry, I never knew how to fix it. Good luck

**Comment by vitaminace33** [comment]
@againpino thx to respond.

@mafintosh, any comment, please?

**Comment by mafintosh** [comment]
should be fixed in latest that upgrades deps. if not reopen

**Comment by vitaminace33** [comment]
I confer that user installation works with minor warnings.
```
user@host:~$ npm install peerflix
npm WARN deprecated parse-torrent-file@2.1.4: Use the parse-torrent package instead
/home/cedricmc
└── peerflix@0.39.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/cedricmc/package.json'
npm WARN cedricmc No description
npm WARN cedricmc No repository field.
npm WARN cedricmc No README data
npm WARN cedricmc No license field.
```
However, system-wide installation `npm install -g peerflix` creates a tree with wrong permissions, owners and broken symlinks at `/usr/local/{lib,bin}`. I believe it is `npm` or distro to blame.

Thx for the fix!

**Comment by vitaminace33** [comment]
I confer that user installation works with minor warnings.
```
user@host:~$ npm install peerflix
npm WARN deprecated parse-torrent-file@2.1.4: Use the parse-torrent package instead
/home/user
└── peerflix@0.39.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/user/package.json'
npm WARN user No description
npm WARN user No repository field.
npm WARN user No README data
npm WARN user No license field.
```
However, system-wide installation `npm install -g peerflix` creates a tree with wrong permissions, owners and broken symlinks at `/usr/local/{lib,bin}`. I believe it is `npm` or distro to blame.

Thx for the fix!
