### ISSUE TITLE
Pause - Resume

### ISSUE THREAD

**Issue by melkir** [mafintosh/peerflix#50]
Hello,
Can you add the possibility to pause and resume an download ?
My connexion is so poor that I can't do anything else on Internet when a download is started.
It would be nice to pause an download with an single key instead of retype the command search for seeder etc :)

Edit : And maybe the possibily to see the progression like 
info downloaded 55.9MB/500MB

**Comment by nfmelendez** [comment]
Hey thanks you, i was looking for this feature, i just have to update :)
