### ISSUE TITLE
Doesn't seem to work with openvpn with Ubuntu

### ISSUE THREAD

**Issue by mihab** [mafintosh/peerflix#98]
Peerflix seems to fail everytime I connect to a VPN via openvpn. Other torrent clients (Transmission for example) do work fine (and everything else as well).

Using Ubuntu 14.04 LTS 64-Bit.

**Comment by mchelen** [comment]
I tested again recently and everything worked fine. This was on Ubuntu 14.04 64 bit.

I've had issues in the past with connecting to UDP trackers over my VPN, maybe that was what caused the original problem.

**Comment by mihab** [comment]
Yes indeed I tried with latest version and seems to work ok now. Closing this ticket.

**Comment by mafintosh** [comment]
:+1:
